--卖出发生额信息  TBIEE_SALE_FS_FACT

-- 纸票转贴现转出发生查询
 SELECT 
 B.PROD_NO AS PROD_NO,
 (CASE 
		WHEN B.PROD_NO IN ('127110','127210','227110','227210') THEN '3' --卖断式
		WHEN B.PROD_NO IN ('127120','127220','227120','227220') THEN '4' --回购式
		WHEN B.PROD_NO IN ('127230','227230') THEN '5' --卖断式再贴现
		WHEN B.PROD_NO IN ('127250','227250') THEN '6' --回购式再贴现
		END) AS PROD_TYPE,
 B.ACCT_BRANCH_NO AS BRCH_NO, NULL AS DEPT_NO,
 B.MAGR_NO AS MAGR_NO,
 TO_CHAR(TO_DATE(B.SALE_DT,'yyyy-MM-dd'),'YYYY"-"MM"-"DD"') AS SALE_DT_STR,
 TO_DATE(B.SALE_DT,'yyyy-MM-dd') AS SALE_DT,
 A.TRANS_ID AS TRANS_ID,B.CUST_NO AS CUST_NO,
 A.IS_SAME_CITY AS LO_CODE,B.IS_INNER AS IO_CODE,
 A.IS_ACCP AS IS_SELF_ACCP,NULL AS IS_BUY_BEFORE,TO_DATE(B.REDEEM_END_DT,'yyyy-MM-dd') AS BUSI_DUE_DT,
 B.RATE AS RATE,B.RATE_TYPE AS RATE_TYPE,A.INTEREST_CAL_DAYS AS RATE_DAYS,
 NULL AS TAX,NULL AS PROFIT,A.BILL_NO AS BILL_NO,A.BILL_TYPE AS BILL_TYPE_CODE,'1' AS BILL_CLASS_CODE,A.BILL_MONEY AS BILL_MONEY,
 TO_DATE(A.ACPT_DT,'yyyy-MM-dd') AS BILL_ACPT_DT,
 TO_DATE(A.DUE_DT,'yyyy-MM-dd') AS BILL_DUE_DT,
 NULL AS BILL_ACPT_CUST_ID,
 (SELECT ACCEPTOR FROM TP_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_ACPT_CUST_NAME,
 (SELECT ACCEPTOR_BANK_NO FROM TP_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_ACPT_BANK_NO,
 A.INTEREST AS INTEREST,NULL AS DRAW_INTEREST,NULL AS NO_DRAW_INTEREST,
 A.REMITTER AS BILL_REMITTER_NAME, A.REMITTER_ACCT_NO AS BILL_REMITTER_ACCT,
 (SELECT REMITTER_BANK_NO FROM TP_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_REMITTER_BANK_NO, 
 (SELECT PAYEE FROM TP_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_PAYEE_NAME, 
 (SELECT PAYEE_ACCT_NO FROM TP_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_PAYEE_ACCT, 
 (SELECT PAYEE_BANK_NO FROM TP_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_PAYEE_BANK_NO, 
 (SELECT PAYEE_BANK_NAME FROM TP_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_PAYEE_BANK_NAME, 
 (SELECT DRAWEE_BANK_NO FROM TP_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_DRAWEE_BANK_NO,
 (SELECT DRAWEE_BANK_NAME FROM TP_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_DRAWEE_BANK_NAME,
 B.IS_USE_CONTRACT AS IS_USE_CONTRACT,
 B.CUST_AREA AS CUST_AREA
 FROM TP_SALE_BILL_INFO A LEFT JOIN TP_SALE_BILL_BATCH B ON A.BATCH_ID=B.ID
WHERE 
A.FLOW_STATUS='FCP27_162'

UNION ALL

-- 电票转贴现转出发生查询
 SELECT 
 B.PROD_NO AS PROD_NO,
 (CASE 
		WHEN B.PROD_NO IN ('127110','127210','227110','227210') THEN '3' --卖断式
		WHEN B.PROD_NO IN ('127120','127220','227120','227220') THEN '4' --回购式
		WHEN B.PROD_NO IN ('127230','227230') THEN '5' --卖断式再贴现
		WHEN B.PROD_NO IN ('127250','227250') THEN '6' --回购式再贴现
		END) AS PROD_TYPE,
 B.ACCT_BRANCH_NO AS BRCH_NO, NULL AS DEPT_NO,
 B.MAGR_NO AS MAGR_NO,
  TO_CHAR(TO_DATE(B.SALE_DT,'yyyy-MM-dd'),'YYYY"-"MM"-"DD"') AS SALE_DT_STR,
 TO_DATE(B.SALE_DT,'yyyy-MM-dd') AS SALE_DT,A.TRANS_ID AS TRANS_ID,B.CUST_NO AS CUST_NO,
 NULL AS LO_CODE,B.IS_INNER AS IO_CODE,
 A.IS_ACCP AS IS_SELF_ACCP,NULL AS IS_BUY_BEFORE,TO_DATE(B.REDEEM_END_DT,'yyyy-MM-dd') AS BUSI_DUE_DT,B.RATE AS RATE,B.RATE_TYPE AS RATE_TYPE,A.INTEREST_CAL_DAYS AS RATE_DAYS,
 NULL AS TAX,NULL AS PROFIT,A.BILL_NO AS BILL_NO,A.BILL_TYPE AS BILL_TYPE_CODE,'2' AS BILL_CLASS_CODE,A.BILL_MONEY AS BILL_MONEY,
 TO_DATE(A.ACPT_DT,'yyyy-MM-dd') AS BILL_ACPT_DT,
 TO_DATE(A.DUE_DT,'yyyy-MM-dd') AS BILL_DUE_DT,
 NULL AS BILL_ACPT_CUST_ID,(SELECT ACCEPTOR FROM TE_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_ACPT_CUST_NAME,(SELECT ACCEPTOR_BANK_NO FROM TE_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_ACPT_BANK_NO,
 A.INTEREST AS INTEREST,NULL AS DRAW_INTEREST,NULL AS NO_DRAW_INTEREST,
 A.REMITTER AS BILL_REMITTER_NAME, A.REMITTER_ACCT_NO AS BILL_REMITTER_ACCT,
 (SELECT REMITTER_BANK_NO FROM TE_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_REMITTER_BANK_NO,
 (SELECT PAYEE FROM TE_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_PAYEE_NAME, 
 (SELECT PAYEE_ACCT_NO FROM TE_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_PAYEE_ACCT, 
 (SELECT PAYEE_BANK_NO FROM TE_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_PAYEE_BANK_NO, 
 (SELECT PAYEE_BANK_NAME FROM TE_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_PAYEE_BANK_NAME, 
 (SELECT DRAWEE_BANK_NO FROM TE_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_DRAWEE_BANK_NO,
 (SELECT DRAWEE_BANK_NAME FROM TE_BILL_INFO WHERE ID=A.BILL_ID) AS BILL_DRAWEE_BANK_NAME,
 B.IS_USE_CONTRACT AS IS_USE_CONTRACT,
  B.CUST_AREA AS CUST_AREA
 FROM TE_SALE_BILL_INFO A LEFT JOIN TE_SALE_BILL_BATCH B ON A.BATCH_ID=B.ID
WHERE 
 A.FLOW_STATUS='FCE27_162'
