-- 金融机构票据业务统计季报表_基础
-- shenzl 20140326
-- 重新修正(20140412)
-- 期末余额 当季发生额 年累计发生额

-- 银行承兑汇票 汇总 
SELECT
	TR.THE_DAY AS BUILD_DAY,
	'0101' AS ITEM,  --银承汇总
	(SELECT DECODE(SUM(TA.BILL_MONEY),NULL,0,SUM(TA.BILL_MONEY)) FROM TBIEE_ACPT_YE_FACT TA WHERE TA.YE_DT = TR.THE_DAY) AS SUM_DQ, --当期余额
	(SELECT DECODE(SUM(TA.BILL_MONEY),NULL,0,SUM(TA.BILL_MONEY)) FROM TBIEE_ACPT_YE_FACT TA 
		WHERE TA.YE_DT = TR.FIRST_YEAR) AS SUM_NC, --年初余额
	(SELECT DECODE(SUM(TA.BILL_MONEY),NULL,0,SUM(TA.BILL_MONEY)) FROM TBIEE_ACPT_FSE_FACT TA 
		WHERE TA.ACPT_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER) AS SUM_DJ, --当季发生额
	(SELECT DECODE(SUM(TA.BILL_MONEY),NULL,0,SUM(TA.BILL_MONEY)) FROM TBIEE_ACPT_FSE_FACT TA 
		WHERE TA.ACPT_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY) AS SUM_NF --年累计发生额	

	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY
-- 承兑保证金/存单质押 

-- 贴现及买断式转贴现 汇总
UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0104' AS ITEM, --贴现及买断式转贴现 汇总
	((SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE (TB.PROD_TYPE='1' OR (TB.PROD_TYPE='2' AND SUBSTR(TB.PROD_NO,5,1)='1')) 
			AND TB.YE_DT=TR.THE_DAY)
		+
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND TB.PROD_TYPE='3') 
		)
		AS SUM_DQ,  --当期余额
	((SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE (TB.PROD_TYPE='1' OR (TB.PROD_TYPE='2' AND SUBSTR(TB.PROD_NO,5,1)='1')) 
			AND TB.YE_DT=TR.FIRST_YEAR) 
		+
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND TB.PROD_TYPE='3')
		)
		AS SUM_NC,  --年初余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM VBIEE_BUYORSALE_FS TB 
		WHERE TB.OPR_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER AND TRAN_FLAG='1') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM VBIEE_BUYORSALE_FS TB 
		WHERE TB.OPR_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY AND TRAN_FLAG='1') AS SUM_DJ  --年累计发生额
			
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY
	

-- 贴现 汇总
UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0105' AS ITEM, --贴现 汇总
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND TB.PROD_TYPE='1') AS SUM_DQ,  --当期余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND TB.PROD_TYPE='1') AS SUM_NC,  --年初余额		
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER
			AND TB.PROD_TYPE='1') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY
			AND TB.PROD_TYPE='1') AS SUM_DJ  --年累计发生额
			
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY


-- 异地贴现
-- 贴现暂无区分同城异地

-- 银票/商票
UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0107' AS ITEM, --贴现 银票
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND TB.PROD_TYPE='1' AND TB.BILL_TYPE_CODE='1') AS SUM_DQ,  --当期余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND TB.PROD_TYPE='1' AND TB.BILL_TYPE_CODE='1') AS SUM_NC, --年初余额 
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER
			AND TB.PROD_TYPE='1' AND TB.BILL_TYPE_CODE='1') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY
			AND TB.PROD_TYPE='1' AND TB.BILL_TYPE_CODE='1') AS SUM_DJ  --年累计发生额
	
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY

UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0108' AS ITEM, --贴现 商票
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND TB.PROD_TYPE='1' AND TB.BILL_TYPE_CODE='2') AS SUM_DQ,  --当期余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND TB.PROD_TYPE='1' AND TB.BILL_TYPE_CODE='2') AS SUM_NC, --年初余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER
			AND TB.PROD_TYPE='1' AND TB.BILL_TYPE_CODE='2') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY
			AND TB.PROD_TYPE='1' AND TB.BILL_TYPE_CODE='2') AS SUM_DJ  --年累计发生额
	
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY

-- 买断式转入 汇总
UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0109' AS ITEM, --买断式转入 汇总
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND SUBSTR(TB.PROD_NO,5,1)='1' AND TB.PROD_TYPE='2') AS SUM_DQ,  --当期余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND SUBSTR(TB.PROD_NO,5,1)='1' AND TB.PROD_TYPE='2') AS SUM_NC,  --年初余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER
			AND SUBSTR(TB.PROD_NO,5,1)='1' AND TB.PROD_TYPE='2') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY
			AND SUBSTR(TB.PROD_NO,5,1)='1' AND TB.PROD_TYPE='2') AS SUM_DJ  --年累计发生额
	
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY

-- 异地

-- 系统外
UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0111' AS ITEM, --买断式转入 系统外
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND SUBSTR(TB.PROD_NO,4,2)='21' AND TB.PROD_TYPE='2') AS SUM_DQ,  --当期余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND SUBSTR(TB.PROD_NO,4,2)='21' AND TB.PROD_TYPE='2') AS SUM_NC,  --年初余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER
			AND SUBSTR(TB.PROD_NO,4,2)='21' AND TB.PROD_TYPE='2') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY
			AND SUBSTR(TB.PROD_NO,4,2)='21' AND TB.PROD_TYPE='2') AS SUM_DJ  --年累计发生额
	
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY

-- 银票/商票 
UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0112' AS ITEM, --买断式转入 银票
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND SUBSTR(TB.PROD_NO,5,1)='1' AND TB.PROD_TYPE='2' AND TB.BILL_TYPE_CODE='1') AS SUM_DQ,  --当期余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND SUBSTR(TB.PROD_NO,5,1)='1' AND TB.PROD_TYPE='2' AND TB.BILL_TYPE_CODE='1') AS SUM_NC,  --年初余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER
			AND SUBSTR(TB.PROD_NO,5,1)='1' AND TB.PROD_TYPE='2' AND TB.BILL_TYPE_CODE='1') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY
			AND SUBSTR(TB.PROD_NO,5,1)='1' AND TB.PROD_TYPE='2' AND TB.BILL_TYPE_CODE='1') AS SUM_DJ  --年累计发生额
	
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY

UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0113' AS ITEM, --买断式转入 商票
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND SUBSTR(TB.PROD_NO,5,1)='1' AND TB.PROD_TYPE='2' AND TB.BILL_TYPE_CODE='2') AS SUM_DQ,  --当期余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND SUBSTR(TB.PROD_NO,5,1)='1' AND TB.PROD_TYPE='2' AND TB.BILL_TYPE_CODE='2') AS SUM_NC,  --年初余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER
			AND SUBSTR(TB.PROD_NO,5,1)='1' AND TB.PROD_TYPE='2' AND TB.BILL_TYPE_CODE='2') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY
			AND SUBSTR(TB.PROD_NO,5,1)='1' AND TB.PROD_TYPE='2' AND TB.BILL_TYPE_CODE='2') AS SUM_DJ  --年累计发生额
	
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY

-- 买断式转出  汇总
UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0114' AS ITEM, --买断式转出 汇总
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND TB.PROD_TYPE='3') AS SUM_DQ,  --当期余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND TB.PROD_TYPE='3') AS SUM_NC,  --年初余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_FS_FACT TB 
		WHERE TB.SALE_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER AND TB.PROD_TYPE='3') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_FS_FACT TB 
		WHERE TB.SALE_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY AND TB.PROD_TYPE='3') AS SUM_DJ  --年累计发生额
	
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY

-- 异地

-- 系统外
UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0116' AS ITEM, --买断式转出 系统外
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND TB.PROD_TYPE='3' AND TB.IO_CODE='0') AS SUM_DQ,  --当期余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND TB.PROD_TYPE='3' AND TB.IO_CODE='0') AS SUM_NC,  --年初余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_FS_FACT TB 
		WHERE TB.SALE_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER AND TB.IO_CODE='0' AND TB.PROD_TYPE='3') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_FS_FACT TB 
		WHERE TB.SALE_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY AND TB.IO_CODE='0' AND TB.PROD_TYPE='3') AS SUM_DJ  --年累计发生额
	
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY

-- 回购式转贴现 汇总
UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0117' AS ITEM, --回购式转贴现 汇总
	((SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE (TB.PROD_TYPE='2' AND SUBSTR(TB.PROD_NO,5,1)='2') 
			AND TB.YE_DT=TR.THE_DAY)
		+
		(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND TB.PROD_TYPE='4')
		)	
		AS SUM_DQ,  --当期余额
	((SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE (TB.PROD_TYPE='2' AND SUBSTR(TB.PROD_NO,5,1)='2') 
			AND TB.YE_DT=TR.FIRST_YEAR)
		+
		(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND TB.PROD_TYPE='4')
		)
			AS SUM_NC,  --年初余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM VBIEE_BUYORSALE_FS TB 
		WHERE TB.OPR_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER AND TRAN_FLAG='2') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM VBIEE_BUYORSALE_FS TB 
		WHERE TB.OPR_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY AND TRAN_FLAG='2') AS SUM_DJ  --年累计发生额
	
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY

-- 买入返售 汇总
UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0118' AS ITEM, --买入返售 汇总
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND SUBSTR(TB.PROD_NO,5,1)='2' AND TB.PROD_TYPE='2') AS SUM_DQ,  --当期余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND SUBSTR(TB.PROD_NO,5,1)='2' AND TB.PROD_TYPE='2') AS SUM_NC,  --年初余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER
			AND SUBSTR(TB.PROD_NO,5,1)='2' AND TB.PROD_TYPE='2') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY
			AND SUBSTR(TB.PROD_NO,5,1)='2' AND TB.PROD_TYPE='2') AS SUM_DJ  --年累计发生额
	
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY

-- 异地
-- 系统外
UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0120' AS ITEM, --买断式转入 系统外
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND SUBSTR(TB.PROD_NO,4,2)='22' AND TB.PROD_TYPE='2') AS SUM_DQ,  --当期余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND SUBSTR(TB.PROD_NO,4,2)='22' AND TB.PROD_TYPE='2') AS SUM_NC,  --年初余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER
			AND SUBSTR(TB.PROD_NO,4,2)='22' AND TB.PROD_TYPE='2') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_BUY_FS_FACT TB 
		WHERE TB.BUY_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY
			AND SUBSTR(TB.PROD_NO,4,2)='22' AND TB.PROD_TYPE='2') AS SUM_DJ  --年累计发生额
	
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY

-- 国有/商行/外资/其它 group by

-- 卖出回购 汇总
UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0125' AS ITEM, --卖出回购 汇总
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND TB.PROD_TYPE='4') AS SUM_DQ,  --当期余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND TB.PROD_TYPE='4') AS SUM_NC,  --年初余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_FS_FACT TB 
		WHERE TB.SALE_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER 
			AND TB.PROD_TYPE='4') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_FS_FACT TB 
		WHERE TB.SALE_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY 
			AND TB.PROD_TYPE='4') AS SUM_DJ  --年累计发生额
	
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY

-- 异地
-- 系统外
UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0127' AS ITEM, --卖出回购 系统外
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND TB.IO_CODE='0' AND TB.PROD_TYPE='5') AS SUM_DQ,  --当期余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND TB.IO_CODE='0' AND TB.PROD_TYPE='5') AS SUM_NC,  --年初余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_FS_FACT TB 
		WHERE TB.SALE_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER 
			AND TB.IO_CODE='0' AND TB.PROD_TYPE='4') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_FS_FACT TB 
		WHERE TB.SALE_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY 
			AND TB.IO_CODE='0' AND TB.PROD_TYPE='4') AS SUM_DJ  --年累计发生额
	
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY

-- 国有/商行/外资/其它 group by

-- 再贴现 汇总
UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0132' AS ITEM, --再贴现 汇总
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND TB.PROD_TYPE IN ('5','6')) AS SUM_DQ,  --当期余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND TB.PROD_TYPE IN ('5','6')) AS SUM_NC,  --年初余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_FS_FACT TB 
		WHERE TB.SALE_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER 
			AND TB.PROD_TYPE IN ('5','6')) AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_FS_FACT TB 
		WHERE TB.SALE_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY 
			AND TB.PROD_TYPE IN ('5','6')) AS SUM_DJ  --年累计发生额
	
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY

-- 卖出回购
UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0133' AS ITEM, --卖出回购式再贴现
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND TB.PROD_TYPE='6') AS SUM_DQ,  --当期余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND TB.PROD_TYPE='6') AS SUM_NC,  --年初余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_FS_FACT TB 
		WHERE TB.SALE_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER 
			AND TB.PROD_TYPE='6') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_FS_FACT TB 
		WHERE TB.SALE_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY 
			AND TB.PROD_TYPE='6') AS SUM_DJ  --年累计发生额
	
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY

-- 银票/商票
UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0134' AS ITEM, --再贴现 银票
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND TB.PROD_TYPE IN ('5','6') AND TB.BILL_TYPE_CODE='1') AS SUM_DQ,  --当期余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND TB.PROD_TYPE IN ('5','6') AND TB.BILL_TYPE_CODE='1') AS SUM_NC,  --年初余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_FS_FACT TB 
		WHERE TB.SALE_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER 
			AND TB.PROD_TYPE IN ('5','6') AND TB.BILL_TYPE_CODE='1') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_FS_FACT TB 
		WHERE TB.SALE_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY 
			AND TB.PROD_TYPE IN ('5','6') AND TB.BILL_TYPE_CODE='1') AS SUM_DJ  --年累计发生额
	
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY

UNION ALL
SELECT 
	TR.THE_DAY AS BUILD_DAY,
	'0135' AS ITEM, --再贴现 商票
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.THE_DAY
			AND TB.PROD_TYPE IN ('5','6') AND TB.BILL_TYPE_CODE='2') AS SUM_DQ,  --当期余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_YE_FACT TB 
		WHERE TB.YE_DT=TR.FIRST_YEAR
			AND TB.PROD_TYPE IN ('5','6') AND TB.BILL_TYPE_CODE='2') AS SUM_NC,  --年初余额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_FS_FACT TB 
		WHERE TB.SALE_DT BETWEEN TR.FIRST_QUARTER AND TR.END_QUARTER 
			AND TB.PROD_TYPE IN ('5','6') AND TB.BILL_TYPE_CODE='2') AS SUM_DJ,  --当季发生额
	(SELECT DECODE(SUM(TB.BILL_MONEY),NULL,0,SUM(TB.BILL_MONEY)) FROM TBIEE_SALE_FS_FACT TB 
		WHERE TB.SALE_DT BETWEEN TR.FIRST_YEAR AND TR.THE_DAY 
			AND TB.PROD_TYPE IN ('5','6') AND TB.BILL_TYPE_CODE='2') AS SUM_DJ  --年累计发生额
	
	FROM TBIEE_WORKDATE TW, TBIEE_REPORT_DATE TR WHERE TR.THE_DAY = TW.WORKDAY
