--最终版全行汇总票据转帖现统计表_基础  TBIEE_ZTXYWSY
--买入返售  余额		
SELECT
	C.TODAY AS BUILD_DAY,
	A.BRCH_NO AS BRCH_NO,
	'1701' AS PROD_TYPE,
	'1' AS CALC_TYPE,
	COUNT(A.ID) AS TOTAL_COUNT,
	SUM(A.BILL_MONEY) AS SUN_MONEY,
	NULL AS INCOME
	FROM TBIEE_BUY_YE_FACT A,
		(SELECT WORKDAY TODAY,TRUNC(WORKDAY,'MONTH') FIRST_DAY FROM TBIEE_WORKDATE) C 
	WHERE A.YE_DT=C.TODAY 
		AND SUBSTR(A.PROD_NO,5,1) IN ('2','9')
		AND A.PROD_TYPE='2' GROUP BY A.BRCH_NO,C.TODAY
UNION ALL		
--买入返售 发生额 		
SELECT
	C.TODAY AS BUILD_DAY,
	A.BRCH_NO AS BRCH_NO,
	'1701' AS PROD_TYPE,
	'2' AS CALC_TYPE,
	COUNT(A.ID) AS TOTAL_COUNT,
	SUM(A.BILL_MONEY) AS SUN_MONEY,
	SUM(A.PROFIT) AS INCOME
	FROM TBIEE_BUY_FS_FACT A,
		(SELECT WORKDAY TODAY,TRUNC(WORKDAY,'MONTH') FIRST_DAY FROM TBIEE_WORKDATE) C 
	WHERE A.BUY_DT BETWEEN C.FIRST_DAY AND C.TODAY
		AND SUBSTR(A.PROD_NO,5,1) IN ('2','9')
		AND A.PROD_TYPE='2' GROUP BY A.BRCH_NO,C.TODAY
UNION ALL
--卖出回购 发生额 		
SELECT
	C.TODAY AS BUILD_DAY,
	A.BRCH_NO AS BRCH_NO,
	'1702' AS PROD_TYPE,
	'2' AS CALC_TYPE,
	COUNT(A.ID) AS TOTAL_COUNT,
	SUM(A.BILL_MONEY) AS SUN_MONEY,
	SUM(A.INTEREST) AS INCOME
	FROM TBIEE_SALE_FS_FACT A,
		(SELECT WORKDAY TODAY,TRUNC(WORKDAY,'MONTH') FIRST_DAY FROM TBIEE_WORKDATE) C 
	WHERE A.SALE_DT BETWEEN C.FIRST_DAY AND C.TODAY
		AND SUBSTR(A.PROD_NO,5,1) IN ('2','9')
		GROUP BY A.BRCH_NO,C.TODAY
		
UNION ALL
--买断转入  余额		
SELECT
	C.TODAY AS BUILD_DAY,
	A.BRCH_NO AS BRCH_NO,
	'1703' AS PROD_TYPE,
	'1' AS CALC_TYPE,
	COUNT(A.ID) AS TOTAL_COUNT,
	SUM(A.BILL_MONEY) AS SUN_MONEY,
	NULL AS INCOME
	FROM TBIEE_BUY_YE_FACT A,
		(SELECT WORKDAY TODAY,TRUNC(WORKDAY,'MONTH') FIRST_DAY FROM TBIEE_WORKDATE) C 
	WHERE A.YE_DT=C.TODAY 
		AND SUBSTR(A.PROD_NO,5,1) NOT IN ('2','3','9') 
		AND A.PROD_TYPE='2' GROUP BY A.BRCH_NO,C.TODAY
UNION ALL		
--买断转入 发生额 		
SELECT
	C.TODAY AS BUILD_DAY,
	A.BRCH_NO AS BRCH_NO,
	'1703' AS PROD_TYPE,
	'2' AS CALC_TYPE,
	COUNT(A.ID) AS TOTAL_COUNT,
	SUM(A.BILL_MONEY) AS SUN_MONEY,
	SUM(A.PROFIT) AS INCOME
	FROM TBIEE_BUY_FS_FACT A,
		(SELECT WORKDAY TODAY,TRUNC(WORKDAY,'MONTH') FIRST_DAY FROM TBIEE_WORKDATE) C 
	WHERE A.BUY_DT BETWEEN C.FIRST_DAY AND C.TODAY
		AND SUBSTR(A.PROD_NO,5,1) NOT IN ('2','3','9')
		AND A.PROD_TYPE='2' GROUP BY A.BRCH_NO,C.TODAY
UNION ALL
--卖断转出 发生额 		
SELECT
	C.TODAY AS BUILD_DAY,
	A.BRCH_NO AS BRCH_NO,
	'1704' AS PROD_TYPE,
	'2' AS CALC_TYPE,
	COUNT(A.ID) AS TOTAL_COUNT,
	SUM(A.BILL_MONEY) AS SUN_MONEY,
	SUM(A.INTEREST) AS INCOME
	FROM TBIEE_SALE_FS_FACT A,
		(SELECT WORKDAY TODAY,TRUNC(WORKDAY,'MONTH') FIRST_DAY FROM TBIEE_WORKDATE) C 
	WHERE A.SALE_DT BETWEEN C.FIRST_DAY AND C.TODAY
		AND SUBSTR(A.PROD_NO,5,1) NOT IN ('2','3','5','9')
		GROUP BY A.BRCH_NO,C.TODAY
		
UNION ALL

--再贴现 余额 		
SELECT
	C.TODAY AS BUILD_DAY,
	A.BRCH_NO AS BRCH_NO,
	'1705' AS PROD_TYPE,
	'1' AS CALC_TYPE,
	COUNT(A.ID) AS TOTAL_COUNT,
	SUM(A.BILL_MONEY) AS SUN_MONEY,
	NULL AS INCOME
	FROM TBIEE_SALE_FS_FACT A,
		(SELECT WORKDAY TODAY,TRUNC(WORKDAY,'MONTH') FIRST_DAY FROM TBIEE_WORKDATE) C 
	WHERE A.SALE_DT BETWEEN C.FIRST_DAY AND C.TODAY
		AND SUBSTR(A.PROD_NO,5,1)='3'
		GROUP BY A.BRCH_NO,C.TODAY
		
UNION ALL
--再贴现 发生额 				
SELECT
	C.TODAY AS BUILD_DAY,
	A.BRCH_NO AS BRCH_NO,
	'1705' AS PROD_TYPE,
	'2' AS CALC_TYPE,
	COUNT(A.ID) AS TOTAL_COUNT,
	SUM(A.BILL_MONEY) AS SUN_MONEY,
	NULL AS INCOME
	FROM TBIEE_SALE_FS_FACT A,
		(SELECT WORKDAY TODAY,TRUNC(WORKDAY,'MONTH') FIRST_DAY FROM TBIEE_WORKDATE) C 
	WHERE A.SALE_DT BETWEEN C.FIRST_DAY AND C.TODAY
		AND SUBSTR(A.PROD_NO,5,1)='3'
		GROUP BY A.BRCH_NO,C.TODAY
